name: Script cron

on:
    schedule:
        - cron: "0 */12 * * *"

    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run the script
              run: bash script.sh

            - name: Display structure of downloaded files
              run: ls -R
              working-directory: databases

            - name: Upload files
              uses: actions/upload-artifact@v2
              with:
                  name: databases
                  path: databases
