name: Script cron

on:
    schedule:
        - cron: "0 */12 * * *"

    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run the script
              run: bash script.sh

            - name: Upload files
              uses: actions/upload-artifact@v2
              with:
                  path: databases

            - name: Update release
              uses: IsaacShelton/update-existing-release@v1.3.2
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  release: latest
                  tag: latest
                  replace: true
                  files: >
                      databases/user.csv
                      databases/user_wo_diacritics.csv
                      databases/user_PL_wo_diacritics.csv
