name: Script cron

on:
    schedule:
        - cron: "0 */12 * * *"

    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run the script
              run: bash script.sh

            - name: Display structure of downloaded files
              run: ls -R
              working-directory: databases

            - name: Upload user.csv
              uses: actions/download-artifact@v3
              with:
                  name: user.csv

            - name: Upload user_wo_diacritics.csv
              uses: actions/download-artifact@v3
              with:
                  name: user_wo_diacritics.csv

            - name: Upload user_PL_wo_diacritics.csv
              uses: actions/download-artifact@v3
              with:
                  name: user_PL_wo_diacritics.csv
